version: '3.8'

services:
  nginx:
    build: .
    env_file:
      - .env
    volumes:
      - nginx_data:/etc/nginx
      - nginx_cert:/acme.sh
      - ./conf.d:/etc/nginx/conf.d
      - ./renew_certificates.sh:/renew_certificates.sh
    ports:
      - "80:80"
      - "443:443"
        #entrypoint: /renew_certificates.sh

volumes:
  nginx_data:
  nginx_cert:
